{
  _meta {
    hasIndexingErrors
    block { number }
    deployment
  }
  pools(first: 5, orderBy: createdAtTimestamp, orderDirection: desc) {
    id
    version
    createdAtTimestamp
    token0 { id symbol }
    token1 { id symbol }
    feeTierBps
    tickSpacing
  }
}
